title: Dcos uXcale
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: sheilammg
repository: sheilammg/Uxcale-Docs

# Build settings
# theme: just-the-docs
plugins:
  - jekyll-feed

# Remote settings
remote_theme: pmarsceill/just-the-docs

permalink: pretty

aux_links:
  "Inditex Tech on GitHub":
    - "//github.com/sheilammg"
    
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
