title: Dcos uXcale
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: sheilammg
repository: sheilammg/Uxcale-Docs

aux_links:
  "Inditex Tech on GitHub":
    - "//github.com/sheilammg"


# Build settings
# theme: just-the-docs
plugins:
  - jekyll-feed
