title: Definicion Ecosistema
theme: just-the-docs

plugins:
  - jekyll-default-layout
  
layout: default
nav_order: 3
grand_parent: Defincion Ecosistema
has_children: true
url: https://sheilammg/Uxcale-Docs/edit/main/docs/Definición%20Ecosistema
